@startuml
class Circle {
}
abstract class Shape {
- String color
- boolean filled
+ String getColor()
+ void setColor(String)
+ boolean isFilled()
+ void setFilled(boolean)
}
class Main {
}


Shape <|-- Circle
@enduml